# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='题目')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
                ('limit', models.CharField(max_length=10, verbose_name='权限')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='更改时间')),
                ('content', models.TextField(verbose_name='博客的内容')),
                ('introduce', models.CharField(max_length=90, verbose_name='博客内容介绍')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
