# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20190709_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='introduce',
            field=models.CharField(max_length=90, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='limit',
            field=models.CharField(max_length=10, verbose_name='文章权限'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, verbose_name='文章标题'),
        ),
    ]
